### ISSUE TITLE
Can't get this to work in my app [Vue v2]

### ISSUE THREAD

**Issue by geoidesic** [vinayakkulkarni/v-offline#1034]
If I try use this in my app, I  just see this in the console:
```
[Vue warn]: Failed to mount component: template or render function not defined.
```

I tried copying your whole example and replacing my component with that, which kinda worked, but I still get this warning:
```
Property or method "wrapperClass" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.
```

And even then, if I set the initial `online` state = false, it never changes... so it is not detecting online status. This is also true in the code sandbox demo.

Changing the network status (e.g. switching off WiFi) has no effect.

**Comment by vinayakkulkarni** [comment]
Can you please create a codesandbox or stackblitz repro demo?

**Comment by reekoz** [comment]
I've made a stackblitz that reproduces the issue https://stackblitz.com/edit/vue2-vue-cli-hog9r3?file=src/App.vue

Check DevTools Console (F12) of the page to see the error

![image](https://user-images.githubusercontent.com/29949267/182840225-90ecb596-b044-4efa-8d53-0db69ec376af.png)

**Comment by vinayakkulkarni** [comment]
For < `v2.3.0`, you need to have VueCompositionApi to be added before using v-offline component., for v2.4.0 which requires vue 2.7, you don't have to use VueCompositionApi anymore as it is part of Vue 2.7.x
