### ISSUE TITLE
Not Trigger change slot

### ISSUE THREAD

**Issue by Iyongbudiarso** [vinayakkulkarni/v-offline#13]
Not trigger change slot.
Just change name variable onLine to isOnline

**Comment by diego-lipinski-de-castro** [comment]
any update on this?

**Comment by guillaumech** [comment]
@vinayakkulkarni there is a pending merge request that fixes this issue, could you please approve it?

**Comment by Iyongbudiarso** [comment]
@diego-lipinski-de-castro you can use this component
https://raw.githubusercontent.com/Iyongbudiarso/v-offline/56fa69d131d04dbbee9d825ae9a996a48e75dd6c/src/VOffline.vue

**Comment by probil** [comment]
Any reason why this happens? And how renaming the variable can fix the problem? In general, `isOnline` name looks better for me and I agree with rename.

**Comment by vinayakkulkarni** [comment]
Sorry guys, been really busy with work. Will check the PR
