### ISSUE TITLE
Always show's me online

### ISSUE THREAD

**Issue by mhetreramesh** [vinayakkulkarni/v-offline#16]
I did the setup as mentioned but always shows me online even I turned off wifi. What could be the posible reason?

**Comment by vinayakkulkarni** [comment]
Can you please try with the updated version? 

Check out the [example](https://github.com/vinayakkulkarni/v-offline/blob/master/example/App.vue)

**Comment by vinayakkulkarni** [comment]
Closing till reply from OP

**Comment by papakay** [comment]
I'm having similar issue with the updated version. (1.1.0). The example link is not working - https://www.webpackbin.com/bins/-KtzX1SZ1VoIwClyWhlR

**Comment by vinayakkulkarni** [comment]
@papakay can you please try with this example: https://github.com/vinayakkulkarni/v-offline/blob/master/example/App.vue

I'll fix the webpackbin link later this week

**Comment by papakay** [comment]
Thanks @vinayakkulkarni. It's still the same issue. Only shows online. However i used an `if` statement with the `onLine`  inside the online template to determine the offline status.

Thanks.

**Comment by querkmachine** [comment]
Realise this is old and closed, but I still have this problem with the most recent version. The offline slot is never displayed, even if the page is loaded without network connectivity. The same is true of [the demo page](https://vinayakkulkarni.github.io/offline/).

As @papakay notes, putting an `if` inside of the online slot does work, but this rather negates the point of having two slots. 

I'm using Firefox 48 on macOS 10.15, if that helps any.
