### ISSUE TITLE
Not detecting connectivity

### ISSUE THREAD

**Issue by nicolasvahidzein** [vinayakkulkarni/v-offline#20]
Hello,

decided to try your package after reading an alligator.io article but i'm sad to report it's not working. Can you offer any advice?

Also, can't it be programmatic instead of DOM dependent?

Thanks.

**Comment by vinayakkulkarni** [comment]
Have you tried with the example mentioned in readme?

https://github.com/vinayakkulkarni/v-offline/blob/master/README.md#white_check_mark-example-1-four_leaf_clover

The alligator.io article is quite old. New version of v-offline uses slots in a better way.

**Comment by nicolasvahidzein** [comment]
Ok will do it now and report back.

Cheers.

**Comment by nicolasvahidzein** [comment]
nothing is showing up sadly. No error but also no display.

**Comment by nicolasvahidzein** [comment]
Can you please post a working demo and code we can run please? I'd love to use your package but it's not working with the sample code provided.

**Comment by nicolasvahidzein** [comment]
Tracing the event in the detect method shows nothing. Very strange. Don't stress out, i'll use window.online for now.

**Comment by raphaelkieling** [comment]
Here i have the same problem

**Comment by nicolasvahidzein** [comment]
@raphaelkieling pink me on gmail (nicolaszein) i'll guide you to a better solution.

**Comment by raphaelkieling** [comment]
I'm glad to hear that, but I found a better solution creating a component that implements window functions and scoped templates :grinning:

**Comment by nicolasvahidzein** [comment]
@raphaelkieling that's exactly what i was going to tell you. Good on you.
