### ISSUE TITLE
usage of pre-compiled template or render function

### ISSUE THREAD

**Issue by probil** [vinayakkulkarni/v-offline#3]
First of all. Thanks for your plugin. It's good!
I got an issue while using it:
```
[Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.
```
Please, could you use one of those options?

**Comment by vinayakkulkarni** [comment]
I'll look into it hopefully this weekend.

**Comment by SgtPepper27** [comment]
Have you solved the problem? Having the same warning.

**Comment by vinayakkulkarni** [comment]
Have you guys tried using proper version of `vue`

See: [this](https://github.com/vuejs-templates/webpack/blob/develop/template/build/webpack.base.conf.js#L34:L42)
```
  resolve: {
    extensions: ['.js', '.vue', '.json'],
    alias: {
      'vue$': 'vue/dist/vue.esm.js',
      '@': resolve('src'),
    }
  },
```

**Comment by probil** [comment]
@vinayakkulkarni Yes, it could work but you should not force users to use standalone version of vue. You plugin is pretty simple and it's possible to write render function by hand in few lines or precompile.
I can help you by PR if you wish

**Comment by vinayakkulkarni** [comment]
Please feel free to send in a PR.

I’ve been super heavily swamped at work and haven’t been able to pay much attention to Open Source Contributions lately.

**Comment by probil** [comment]
But Open Source Contributions pays more in long run 😄 
In any case you should just decide what is better for the plugin render function or precompile 🤔

**Comment by probil** [comment]
> Please feel free to send in a PR.
Ok. I will create few PRs soon)

**Comment by probil** [comment]
Precompile may be better because as a side effect we will be able to user ES6+ features

**Comment by probil** [comment]
PR is here https://github.com/vinayakkulkarni/v-offline/pull/5

**Comment by vinayakkulkarni** [comment]
@probil: Merged. Drafted new release too. Thanks.
