### ISSUE TITLE
Attach v-if directly to slots and avoid useless nestings

### ISSUE THREAD

**Issue by probil** [vinayakkulkarni/v-offline#4]
You should avoid nesting where possible because plugin user are forced to apply additional styles to wrapper `div`.

Let's say we have current template and usage of plugin this way:
```vue
<detect-network online-class="online" offline-class="offline">
  <div slot="online">You are online!</div>
  <div slot="offline">You are offline!</div>
</detect-network>
```
If browser is online, rendered html will lool like this:
```html
<div>
  <div class="offline">
    You are online!
  </div>
</div>
```
There is two wrappers of `You are online!` which is not good

**Comment by probil** [comment]
Actually we may get only 1 or even 0 😄 
But the plugin user will have even more control of plugin & styling.

1)**Template with only 1 wrapper**
```vue
<template>
  <div :class="{onlineClass: onLine, offlineClass: !onLine}">
    <slot
      v-if="onLine"
      name="online"
    />
    <slot
      v-else
      name="offline"
    />
  </div>
</template>
```
And rendered html will look like this:
```html
<div class="offline">
  You are online!
</div>
```

2)**Template with 0 wrappers**. Vue actually allows to have 2 root nodes, in case of `v-if + v-else` is used. https://github.com/vuejs/vue/issues/3878 (our case)
But the drawback here is that we should remove `onlineClass`/`offlineClass` feature as vue doen't support attaching classes to slots. :thi It's not actually a big deal as user can always attach it to the content of the scope 
Template:
```vue
<template>
  <slot
    v-if="onLine"
    name="online"
  />
  <slot
    v-else
    name="offline"
  />
</template>
```
Rendered html will look like this:
```html
You are online!
```

**Comment by vinayakkulkarni** [comment]
PR #11 solves this issue.
