### ISSUE TITLE
Just checking connection to router

### ISSUE THREAD

**Issue by pixagraphic** [vinayakkulkarni/v-offline#41]
The plugin will not really show me if I am online or not. It will always show online as long as there is an active wifi/ethernet connection it doesn't matter if the router you're connected to is actually hooked up to the internet or not.

You can easily reproduce this by connecting to your cellphone via hotspot and disable mobile internet on your phone. v-online will report online on your connected computer. Is this the desired behaviour? If so this really should be documented.

**Comment by skourismanolis** [comment]
I had a quick look at the source code and I see that it's using the online/offline event of the browser. The browsers check (as you said) whether the device is connected to a network, and not if the device is connected to the internet. I also think this distinction should be clear in the readme of this repo.

**Comment by Sjoerd82** [comment]
navigator.onLine is not 100% reliable (very unfortunate). To know for sure you will want to do a PING or something like that.

**Comment by vinayakkulkarni** [comment]
I've implemented a ping functionality.

**Comment by pixagraphic** [comment]
Very nice, thanks! I'm going to test this soon.

**Comment by vinayakkulkarni** [comment]
Closing this as it's:
1. Stale
2. Was based on older features
