### ISSUE TITLE
I can't call the network-detect event in the vue lifecycle hooks

### ISSUE THREAD

**Issue by anjayluh** [vinayakkulkarni/v-offline#68]
The network status is not updated on change like the SPA functions

**Comment by Sandman83** [comment]
I have a similar problem, at least I assume that. I'm going to attach some code below. 
```

<template>
    <offline
        online-class="online"
        offline-class="offline"
        @detected-condition="handleConnectivityChange">
        <div slot="online" v-bind:class="[onLine === null ? 'hidden' : (onLine ? 'online' : 'offline')]">
            <span>●</span>
        </div>
        <div slot="offline" v-bind:class="[onLine === null ? 'hidden' : (onLine ? 'online' : 'offline')]">
            <span>●</span>
        </div>
    </offline>
</template>

<script>
    import offline from 'v-offline';
    export default {
        name: "OfflineFlag",
        components: {
            offline
        },
        data: function(){
            return {
                onLine : null
            }
        },
        methods: {
            handleConnectivityChange(status){
                console.log(status);
                this.onLine = status;
            }
        }
    }
</script>

<style scoped>
.online{
    color: green;
}
.offline{
    color: red;
}
.hidden{
    display: none;
    visibility: hidden;
}
</style>
```
On page loading is everything fine. The indicator shows online, as expected. When I turn my internet connection off, also everything is ok, the indicator shows offline. The console output is "ERR_INTERNET_DISCONNECTED", I assume, this is also expected.
Now, the problem: if I turn my internet connection on again, the indicator does not turn to the online state. The console shows "ERR_NAME_NOT_RESOLVED".

**Comment by vinayakkulkarni** [comment]
Should be fixed in the latest version of `v-offline`, you can fork & play with the demo here – https://github.com/vinayakkulkarni/v-offline#demo
