### ISSUE TITLE
Why does package keep appending /favicon.ico?1639758312722

### ISSUE THREAD

**Issue by OyewoleOyedeji** [vinayakkulkarni/v-offline#716]
Testing for connection on the URL `https://jsonplaceholder.typicode.com/todos/1/favicon.ico?1639758312722`

But it fails because the package keeps appending `/favicon.ico?1639758312722` at the end

I use `v-offline@3.0.3`

**Comment by OyewoleOyedeji** [comment]
@vinayakkulkarni is this project dead

**Comment by vinayakkulkarni** [comment]
> @vinayakkulkarni is this project dead

I am a bit preoccupied at work and have been away for OSS, will look in this over the weekend

**Comment by OyewoleOyedeji** [comment]
@vinayakkulkarni Merry Christmas? Have you checked the issue

**Comment by vinayakkulkarni** [comment]
> @vinayakkulkarni Merry Christmas. Have you checked the issue?

It probably has to do something with Ping.js which adds timestamp as query param to the ping url. have to dig deep in the ping.js code to check.

Found it, https://github.com/alfg/ping.js/blob/master/src/ping.js#L81

It's not an issue with this package as such, more of ping.js issue.
