### ISSUE TITLE
Update Examples in README

### ISSUE THREAD

**Issue by vinayakkulkarni** [vinayakkulkarni/v-offline#8]
- [x] Updating the examples
- [x] Updating the [demo site](https://github.com/vinayakkulkarni/offline) with latest v-offline release

**Comment by probil** [comment]
I would like to provide:
- jsfiddle example (without build tool);
- codesandbox example (with webpack);
It's also useful because it may help people show their feature issues easier by creating a minimal working example. It's pretty hard to find the issue sometimes without it.

**Comment by vinayakkulkarni** [comment]
I've already (nearly) finished a jsfiddle and webpackbin.com example

Thanks for the offer though!

**Comment by probil** [comment]
Ok, I've add few fixes to README in new PR #9

**Comment by mirozahorak** [comment]
💯 Webpackbin Link doesn't work
